### ISSUE TITLE
Correct Grammar Mistake

### ISSUE THREAD

**Issue by JerryLin0315** [shenyiego/3#1]
Could you guys please read through the final report and correct grammar mistakes I might have?

Thanks.
Jerry

**Comment by lalapeoplo** [comment]
Everything is  ok!!!!!!! Except of the word “firstly” at the begining second paragraph should be deleted.
Thank you 👍

**Comment by shenyiego** [comment]
Everything is ok too!!!  
In fact,  based on my poor English anything cannot be a problem. just a kidding. hahahahaha

**Comment by shenyiego** [comment]
Just in case, I check it again and correct a little part of data analysis.
